name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cdk
          aws-region: eu-west-1
      - name: Install and build consumer
        run: cd consumer && npm install && npm run build
      - name: Install and build producer
        run: cd producer && npm install && npm run build
      - name: Install and build frontend
        run: cd frontend && npm install && npm run build
      - name: Install and deploy infrastructure
        run: cd infra && npm install && npm run cdk deploy "*"
